# Configuration options for dependency updates from GitHub Dependabot
# https://docs.github.com/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2

updates:
  - directory: / # for .github/workflows
    package-ecosystem: github-actions
    schedule: { interval: daily } # every weekday, Monday thru Friday
