# Prettier formatting options
# https://prettier.io/docs/en/options.html

proseWrap: always # break long markdown lines into shorter ones

overrides:
  - files: "**/.config/gh/*.yml" # `gh` autoformats and rewrites its YAML files
    options: { tabWidth: 4 }
