# GitHub Actions workflow definition
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Pull request

on:
  pull_request:
    branches: [master]

jobs:
  linter:
    name: Super-Linter checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3.14.5
        env:
          FILTER_REGEX_EXCLUDE:
            # Visual Studio Code configuration is JSONC, so exclude those files
            # from `jsonlint`; see https://github.com/zaach/jsonlint/issues/50
            ".*\\.vscode/.+\\.json$"

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for individual lint status
