# GitHub Actions workflow definition
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Pull request

on:
  pull_request:
    branches: [master]

jobs:
  linter:
    name: Super-Linter checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # repository available as $GITHUB_WORKSPACE
      - uses: github/super-linter@v3.15.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for individual lint status

          VALIDATE_JSON:
            # `jsonlint` doesn't support "JSON with comments", as used by Visual
            # Studio Code (see https://github.com/zaach/jsonlint/issues/50), and
            # this repository uses Prettier anyway
            false

          # Some built-in Python-related features from the Super-Linter are
          # disabled here in favor of the "Python checks" below.
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false

  python:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.5" # as on Ubuntu 20.04
      - run: pip install black boto3
      - run: black --check .
      - run: npm ci # use whatever Node environment runner has; shouldn't matter
      - run: node_modules/.bin/pyright
